services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1 #This version includes the legacy web console, good for rebugging. Update to latest / use other object store for production
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000 # API
      - 9001:9001 # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio-data:/data

  redis:
    image: redis:7-alpine
    command: ['redis-server', '--appendonly', 'yes', '--requirepass', 'redis']
    ports:
      - 9002:6379
    volumes:
      - ./redis-data:/data

  postgres:
    image: postgres:17
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: core-cast
    networks:
      - admin
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  # OPTIONAL: Explorer for postgreSQL
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - admin

networks:
  admin:
