{
 "title": "core cast",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Transcoding service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transcoding pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processing_pressure{job=\"transcoding-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "running_tasks{job=\"transcoding-service\"}",
     "legendFormat": "Running tasks"
    },
    {
     "expr": "rate(completed_tasks{job=\"transcoding-service\"}[1m])",
     "legendFormat": "Completed tasks"
    },
    {
     "expr": "rate(errrored_tasks{job=\"transcoding-service\"}[1m])",
     "legendFormat": "Errored tasks"
    }
   ]
  },
  { "title": "Upload service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uploaded files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_files{job=\"upload-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "rate(total_bytes{job=\"upload-service\"}[1m])",
     "legendFormat": "Incoming bytes"
    }
   ]
  },
  {
   "title": "Housekeeping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "Housekeeping tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(completed_tasks{job=\"housekeeping-service\"}[10m])",
     "legendFormat": "Completed tasks (10m)"
    },
    {
     "expr": "rate(errrored_tasks{job=\"housekeeping-service\"}[10m])",
     "legendFormat": "Errored tasks (10m)"
    }
   ]
  }
 ]
}