FROM node:22-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY ./shared/prisma /app
RUN pnpm install
RUN pnpm run build
CMD ["pnpm", "prisma", "migrate", "deploy"]
