global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'upload-service'
    static_configs:
      - targets: ['upload:8081']
  - job_name: 'transcoding-service'
    static_configs:
      - targets: ['transcoding:8081']
